components:
    examples: {}
    headers: {}
    parameters: {}
    requestBodies: {}
    responses: {}
    schemas:
        Area:
            properties:
                id:
                    type: number
                    format: double
                area:
                    type: string
            required:
                - id
                - area
            type: object
            additionalProperties: false
        AreaDto:
            properties:
                id:
                    type: number
                    format: double
                area:
                    type: string
                    example: Pontiank
            required:
                - id
                - area
            type: object
            additionalProperties: false
        PaginationResult_Area_:
            properties:
                total:
                    type: number
                    format: double
                perPage:
                    type: number
                    format: double
                data:
                    items:
                        $ref: '#/components/schemas/Area'
                    type: array
            required:
                - total
                - perPage
                - data
            type: object
            additionalProperties: false
    securitySchemes:
        bearer_auth:
            type: http
            scheme: bearer
            bearerFormat: Bearer
info:
    title: exp
    version: 0.0.0
    license:
        name: MIT
    contact: {}
openapi: 3.0.0
paths:
    /area:
        post:
            operationId: Create
            responses:
                '200':
                    description: Ok
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Area'
            tags:
                - Area
            security:
                - bearer_auth: []
            parameters: []
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            anyOf:
                                - $ref: '#/components/schemas/AreaDto'
                                - {}
        put:
            operationId: Update
            responses:
                '200':
                    description: Ok
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Area'
            tags:
                - Area
            security:
                - bearer_auth: []
            parameters: []
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            anyOf:
                                - $ref: '#/components/schemas/AreaDto'
                                - {}
    '/area/{perPage}/{lastId}/{sort}':
        get:
            operationId: List
            responses:
                '200':
                    description: Ok
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/PaginationResult_Area_'
            tags:
                - Area
            security:
                - bearer_auth: []
            parameters:
                - in: path
                  name: perPage
                  required: true
                  schema:
                      format: double
                      type: number
                - in: path
                  name: lastId
                  required: true
                  schema:
                      format: double
                      type: number
                - in: path
                  name: sort
                  required: true
                  schema:
                      format: double
                      type: number
                - in: query
                  name: search
                  required: false
                  schema:
                      type: string
    '/area/{id}':
        get:
            operationId: View
            responses:
                '200':
                    description: Ok
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Area'
            tags:
                - Area
            security:
                - bearer_auth: []
            parameters:
                - in: path
                  name: id
                  required: true
                  schema:
                      format: double
                      type: number
        delete:
            operationId: Delete
            responses:
                '204':
                    description: 'No content'
            tags:
                - Area
            security:
                - bearer_auth: []
            parameters:
                - in: path
                  name: id
                  required: true
                  schema:
                      format: double
                      type: number
servers:
    - url: /
